{{- if .Values.certmanager.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  destination:
    name: {{ .Values.destination.cluster }}
    namespace: {{ .Values.certmanager.namespace }}
  source:
    path: ''
    repoURL: 'https://charts.jetstack.io'
    targetRevision: '*'
    chart: cert-manager
    helm:
      parameters:
        - name: clusterResourceNamespace
          value: infra-cert-manager
        - name: global.leaderElection.namespace
          value: infra-cert-manager
        - name: installCRDs
          value: 'true'
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
{{- end }}