{{- if .Values.podadmissioncontroller.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pod-admission-controller
spec:
  destination:
    name: {{ .Values.destination.cluster }}
    namespace: {{ .Values.podadmissioncontroller.namespace }}
  source:
    path: helm
    repoURL: 'https://github.com/silviugae/pod-admission-controller.git'
    targetRevision: main
    helm:
      parameters:
        - name: certmanager.namespace
          value: infra-cert-manager
        - name: config.webserver.port
          value: '443'
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
{{- end }}