{{- if .Values.loki.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
spec:
  destination:
    name: {{ .Values.destination.cluster }}
    namespace: {{ .Values.loki.namespace }}
  source:
    path: helm
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: main
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
{{- end }}